idf_component_register(SRCS "../assets/poketch_background.c" 
                    "../assets/poketch_background_2.c" 
                    "../assets/poketch_numeral_64.c" 
                    "hardware_drivers.c"
                    "time_manager.c"
                    "ui_clock_screen.c"
                    "main.c"
                    INCLUDE_DIRS ".")